version: 2

sources:
  - name: Supermercado                                        # conjunto de datos
    database: mewhen-394014                                   # proyecto
    tables:
      - name: Clientes_EXT                                    # tabla
        description: Tabla de información general del viento  # descripción tabla
      - name: Compras_EXT                                     # tabla
        description: Tabla de información general del viento  # descripción tabla
      - name: Olimpica_EXT                                    # tabla
        description: Tabla de información general del viento  # descripción tabla
      - name: Exito_EXT                                       # tabla
        description: Tabla de información general del viento  # descripción tabla