version: 2

sources:
  - name: Supermercado
    database: mewhen-394014
    tables:
      - name: Clientes_EXT
        description: Tabla de la informaci贸n de los clientes 
      - name: Compras_EXT 
        description: Tabla de informaci贸n de las compras realizadas
      - name: Olimpica_EXT
        description: Tabla de informaci贸n inventario de supermercado Olimpica
      - name: Exito_EXT
        description: Tabla de informaci贸n inventario de supermercado Exito